config/routes.rb
Rails.application.routes.draw do
  resources :houses, only: [:index, :new, :edit, :update, :create, :destroy] do
    resources :inspections, only: [:create, :new]
  end
  # resources :inspections, only: [:create, :new]

  # check this out in `rails routes`
  post "houses/search", to: "houses#search"

  get "dashboard", to: "houses#dashboard"

  get "login", to: "sessions#login"
  get "signup", to: "sessions#signup"

  post "sessions/signup", to: "sessions#create"
  post "sessions/login", to: "sessions#authenticate"

  post "logout", to: "sessions#destroy"

  # get "/dashboard", to: "houses#dashboard"

  root to: "houses#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
    validates :username, length: { minimum: 5 }

    # lookup the has_secure_password that abstract the below
    # auto implement a password and password confirmation

    # this + is like a setter method
    # :: namespace resolution operator
    def password=(new_password)
        salt = BCrypt::Engine::generate_salt
        hashed = BCrypt::Engine::hash_secret(new_password, salt)
        self.password_digest = salt + hashed
    end

    def check_admin(password)
        # generate_salt are always 29 chars long
        puts "check_admin"
        puts password
        salt = self.password_digest[0..28]

        puts salt
        hashed = BCrypt::Engine::hash_secret(password, salt)

        puts salt + hashed
        puts self.password_digest
        return (salt + hashed) == self.password_digest
    end

end

app/models/agent.rb
class Agent < ApplicationRecord
    has_and_belongs_to_many :houses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
    has_many :inspections
    has_and_belongs_to_many :agents
end

app/models/inspection.rb
class Inspection < ApplicationRecord
    # validation
    validates :name, length: { minimum: 2 }
    validates :day, presence: true
    validates :house_id, presence: true
    validates :comment, presence: true
    validates :contact, presence: true

    belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def content_not_found
        render file: "#{Rails.root}/public/404.html", layout: true, status: :not_found
    end

    def user_error
        render file: "#{Rails.root}/public/422.html", layout: true, status: :bad_request
    end

    def user_conflict
        render file: "#{Rails.root}/public/409.html", layout: true, status: :conflict
    end

    def user_unauthorized
        render file: "#{Rails.root}/public/401.html", layout: true, status: :unauthorized
    end

    def user_forbidden
        render file: "#{Rails.root}/public/403.html", layout: true, status: :forbidden
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    before_action :set_house, only: %i[ edit update destroy ]
    before_action :require_login
    skip_before_action :require_login, only: [:index, :search]

    layout "main"

    def dashboard
        @houses = House.all
        @agents = Agent.all
        render layout: "admin"
    end

    def index
        # start with
        # @houses = House.all

        @houses = House.where("bed >= ? AND bath >= ? AND garage >= ? AND size >= ? ", 
            extract_value(params, "bed"), extract_value(params, "bath"), extract_value(params, "car"), extract_value(params, "size"))

        # NOTE you can inject other models in here as well 
    end

    def new
        @house = House.new
        render layout: "admin"
    end

    def edit
        render layout: "admin"
    end

    def create
        @house = House.new(house_params)
        if @house.save
            redirect_to '/dashboard'
        else
            user_error
        end
    end

    def update
        if @house.update(house_params)
            redirect_to '/dashboard'
        else
            user_error
        end
    end

    def destroy
        @house.destroy
        redirect_to '/dashboard'
    end

    # search form submission
    def search
        puts "search"
        puts params[:search][:bed]

        redirect_to root_url(search_params)
    end

    private

    # only a trusted list of params here
    def house_params
        params.require(:house).permit(:address, :size, :sold, :bed, :bath, :garage, :image)
    end

    def set_house
        @house = House.find(params[:id])
      end

    def extract_value(params, key)
        val = params.key?(key) && params[key] != "" ? params[key].to_i : 0
        val
    end

    def search_params
        params.require(:search).permit(:bed, :bath, :car, :size)
    end

    def require_login
        return user_forbidden unless session.include? :username
    end

end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
    layout "main"

    def new
    end

    # POST /inspections
    def create
        @inspection = Inspection.new(create_params)

        puts params
        @inspection.house_id = params[:house_id]
        
        if @inspection.valid?
            @inspection.save
            redirect_to root_url
        else
            user_error
        end  
    end

    private

    def create_params
        params.require(:inspection).permit(:name, :day, :comment, :contact)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    layout "application"

    def login
    end

    def signup
    end

    # POST /signup
    def create
        return user_conflict if Admin.where(username: params[:admin][:username]).count > 0

        @admin = Admin.new(create_params)

        if @admin.valid?
            @admin.save
            session[:username] = params[:admin][:username]

            redirect_to '/dashboard'
        else
            user_error
            session.delete :username
        end
    end

    # POST /login
    def authenticate
        # look up user in db
        # verify credentials
        # store userid in the session
        @admin = Admin.find_by(username: params[:admin][:username])

        # if either username or password does not correct
        if @admin.nil? || !@admin.check_admin(params[:admin][:password])
            user_unauthorized
            session.delete :username
        else
            session[:username] = params[:admin][:username]
            redirect_to '/dashboard'
        end  
    end 

    def destroy
        session.delete :username
        redirect_to '/'
    end

    private

    def create_params
        params.require(:admin).permit(:firstname, :lastname, :username, :password)
    end

    def auth_params
        params.require(:admin).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
    def last_updated(house)
        house.updated_at.strftime("%A, %b %e, at %l:%M %p")
    end
end

app/views/forms/_search.html.erb
<h3> Search for your dream home </h3>

<%= form_tag houses_search_path do %>
    <label>Number of bedrooms:</label><br>
    <%= number_field_tag :'search[bed]' %><br>

    <label>Number of bathrooms:</label><br>
    <%= number_field_tag :'search[bath]' %><br>

    <label>Number of car spaces:</label><br>
    <%= number_field_tag :'search[car]' %><br>

    <label>Size of the house:</label><br>
    <%= number_field_tag :'search[size]' %><br>

    <%= submit_tag "Submit Search" %>
<% end %>

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>

    <div class="field">
        <%= form.label :address %>
            <%= form.text_field :address %>
        </div>
    </div>
    
    <div class="field">
        <%= form.label :size %>
            <%= form.number_field :size %>
        </div>
    </div>

    <div class="field">
        <%= form.label :bed %>
            <%= form.number_field :bed %>
        </div>
    </div>

    <div class="field">
        <%= form.label :bath %>
            <%= form.number_field :bath %>
        </div>
    </div>

    <div class="field">
        <%= form.label :car %>
            <%= form.number_field :garage %>
        </div>
    </div>

    <div class="field">
        <%= form.label :image %>
            <%= form.text_field :image %>
        </div>
    </div>

    <div class="field">
        <%= form.label :sold %>
            <%= form.select :sold, [["True", true], ["False", false]] %>
        </div>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
    
<% end %>
  

app/views/houses/_table.html.erb
<br>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Address</th>
      <th>Size</th>
      <th>Sold</th>
      <th>Bedroom</th>
      <th>Bath</th>
      <th>Car</th>
      <th>Image</th>
      <th colspan="1"></th>
      <th>Agents</th>
      <th>Last Updated</th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.id %></td>
        <td><%= house.address %></td>
        <td><%= house.size %></td>
        <td><%= house.sold %></td>
        <td><%= house.bed %></td>
        <td><%= house.bath %></td>
        <td><%= house.garage %></td>
        <td><%= image_tag(house.image, :size => "100x50") %><br /></td>
        <td><%= link_to 'Request Inspection', new_house_inspection_path(house.id) %></td>
        <td> 
            <% house.agents.each do |agent| %>
                <span>
                    <%= agent.name %> 
                    <br>
                </span>
            <% end %>
        </td>
        <td><%= last_updated house %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/houses/dashboard.html.erb
<h2> Welcome to the admin dashboard </h2>

<br>

<h3> Houses </h3>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Address</th>
      <th>Size</th>
      <th>Sold</th>
      <th>Bedroom</th>
      <th>Bath</th>
      <th>Car</th>
      <th>Image</th>
      <th>Agents</th>
      <th>Last Updated</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.id %></td>
        <td><%= house.address %></td>
        <td><%= house.size %></td>
        <td><%= house.sold %></td>
        <td><%= house.bed %></td>
        <td><%= house.bath %></td>
        <td><%= house.garage %></td>
        <td><%= image_tag(house.image, :size => "100x50") %><br /></td>
        <td> 
            <% house.agents.each do |agent| %>
                <span>
                    <%= agent.name %> 
                    <br>
                </span>
            <% end %>
        </td>
        <td><%= last_updated house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Delete', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3> Agents </h3>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Area</th>
      <th>Rating</th>
      <th>Sold</th>
      <th>Last Updated</th>
    </tr>
  </thead>

    <tbody>
    <% @agents.each do |agent| %>
        <tr>
        <td><%= agent.id %></td>
        <td><%= agent.name %></td>
        <td><%= agent.area %></td>
        <td><%= agent.rating %></td>
        <td><%= agent.sold %></td>
        <td><%= last_updated agent %></td>
        </tr>
    <% end %>
    </tbody>
</table>


<br>

app/views/houses/edit.html.erb
<br>
<br>
<%= render 'form', house: @house %>

app/views/houses/index.html.erb
<%= render 'forms/search' %>

<%= render 'table' %>

app/views/houses/new.html.erb
<br>
<br>
<%= render 'form', house: @house %>

app/views/inspections/new.html.erb
<h3> Schedule a new inspection </h3>

<%= form_tag house_inspections_path do %>
    <label>Your name:</label><br>
    <%= text_field_tag :'inspection[name]' %><br>

    <label>Contact number:</label><br>
    <%= text_field_tag :'inspection[contact]' %><br>

    <label>Which day:</label><br>
    <%= text_field_tag :'inspection[day]' %><br>

    <label>Comment:</label><br>
    <%= text_area_tag :'inspection[comment]' %><br>

    <%= submit_tag "Submit Search" %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="admin-menu">
        <h2> Admin menu section here </h2>

        <%= form_tag logout_path do %>
            <%= submit_tag "Log out" %>
        <% end %>

        <%= link_to 'Add new house', new_house_path %>
    </div>

    <%= yield %>

    <div class="admin-footer">
        <h2> Admin footer section here </h2> 
    </div>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="menu">
        <h2> Navigation menu section (TODO: put menu here) </h2>

        <%= link_to 'Log in', login_path %>
        <%= link_to 'Sign up', signup_path %>

    </div>

    <%= yield %>

    <div class="footer">
        <h2> This is the footer section (TODO: put footer here) </h2> 
    </div>
    
  </body>
</html>